const Cuacks = [
    {
        id_cuack: '01',
        uName: 'Juanito Perez',
        uEmail: 'juanito@gmail.com',
        tdes:'Electrodomésticos',
        url: 'www.google.com',
        calification: '5',
        status: 'Visible',
    },
    {
        id_cuack: '02',
        uName: 'Elena Nito Del Bosque',
        uEmail: 'elena@gmail.com',
        tdes:'Productos de Limpieza',
        url: 'www.google.com',
        calification: '3.5',
        status: 'Oculto',
    },
    {
        id_cuack: '03',
        uName: 'Alex Tintor',
        uEmail: 'alex@gmail.com',
        tdes:'Computadoras',
        url: 'www.google.com',
        calification: '5',
        status: 'Visible',
    },
    {
        id_cuack: '04',
        uName: 'Susana Horia',
        uEmail: 'susana@gmail.com',
        tdes:'Dispositivos Móviles',
        url: 'www.google.com',
        calification: '1',
        status: 'Visible',
    },
    {
        id_cuack: '05',
        uName: 'Leon Del Bosque',
        uEmail: 'leon@gmail.com',
        tdes:'Utensilios',
        url: 'www.google.com',
        calification: '4',
        status: 'Visible',
    },
    {
        id_cuack: '06',
        uName: 'Armando Paredes',
        uEmail: 'armando@gmail.com',
        tdes:'Lavados',
        url: 'www.google.com',
        calification: '2.5',
        status: 'Visible',
    }
]